spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/sports_service?serverTimezone=Asia/Seoul
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  jackson:
    property-naming-strategy: SNAKE_CASE



server:
  port: 8181


# log level setting
logging:
  level:
    root: info
    SportsService:
      backend: debug
    org:
      hibernate:
        SQL: debug